using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using UnityEngine.Assertions;

namespace AnyVR.LobbySystem.Internal
{
    internal class QuickConnectHandler
    {
        private readonly Dictionary<uint, Guid> _quickConnectToId = new();

        internal bool RegisterLobby(LobbyState lobby)
        {
            Assert.IsTrue(lobby.LobbyId != Guid.Empty);

            if (_quickConnectToId.ContainsKey(lobby.QuickConnectCode))
                // already registered
                return false;

            // The unique quick connect code is generated by the LobbyFactory.
            Assert.IsFalse(_quickConnectToId.ContainsKey(lobby.QuickConnectCode));

            _quickConnectToId[lobby.QuickConnectCode] = lobby.LobbyId;
            return true;
        }

        internal bool UnregisterLobby(LobbyState lobby)
        {
            return _quickConnectToId.Remove(lobby.QuickConnectCode);
        }

        [CanBeNull]
        internal LobbyState GetLobbyState(uint code)
        {
            if (!_quickConnectToId.TryGetValue(code, out Guid lobbyId))
                return null;

            LobbyState lobby = LobbyManager.Instance.Internal.GetLobbyState(lobbyId);
            Assert.IsNotNull(lobby);
            return lobby;
        }
    }
}
