using System;
using System.Collections.Generic;
using UnityEngine.Assertions;

namespace AnyVR.LobbySystem.Internal
{
    internal class QuickConnectHandler
    {
        private readonly Dictionary<uint, Guid> _quickConnectToId = new();

        internal bool RegisterLobby(GlobalLobbyState globalLobby)
        {
            Assert.IsTrue(globalLobby.LobbyId != Guid.Empty);

            if (_quickConnectToId.ContainsKey(globalLobby.QuickConnectCode))
                // already registered
                return false;

            // The unique quick connect code is generated by the LobbyFactory.
            Assert.IsFalse(_quickConnectToId.ContainsKey(globalLobby.QuickConnectCode));

            _quickConnectToId[globalLobby.QuickConnectCode] = globalLobby.LobbyId;
            return true;
        }

        internal bool UnregisterLobby(GlobalLobbyState globalLobby)
        {
            return _quickConnectToId.Remove(globalLobby.QuickConnectCode);
        }

        internal GlobalLobbyState GetLobbyState(uint code)
        {
            if (!_quickConnectToId.TryGetValue(code, out Guid lobbyId))
                return null;

            GlobalLobbyState globalLobby = LobbyManager.Instance.Internal.GetLobbyState(lobbyId);
            Assert.IsNotNull(globalLobby);
            return globalLobby;
        }
    }
}
